site_name: Architecture Tradeoff Analysis Methodology
site_description: 'DESCRIPTION All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/atam'
repo_url: 'https://github.com/dmccreary/atam'

nav:
  - Home: index.md
  - About: about.md
  - ATAM Process: atam-process.md
  - ATAM DB Selection Process: atam-db-process.md
  - Foundational Concepts:
    - Introduction: concepts/index.md
    - Utility Tree: concepts/utility-tree.md
    - ACID vs. Base: concepts/acid-vs-base.md
  - Database Types:
    - Introduction: db-types/index.md
    - Relational: db-types/01-relational.md
    - Analytical: db-types/02-analytical.md
    - Key Value: db-types/03-key-value.md
    - Column Family: db-types/04-column-family.md
    - Graph: db-types/05-graph.md
    - Document: db-types/06-document.md
  - Case Studies:
    - Introduction: case-studies/index.md
    - STAR Process: case-studies/star-process.md
    - Amazon Shopping Cart: case-studies/amazon-shopping-cart.md
  - Bias: bias.md
  - Presentations: slides.md
  - License: license.md
  - How We Built This Site: how-we-built-this-site.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  extra_css:
    - styles/custom.css
  # logo: img/my-icon.png
  # favicon: img/my-icon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX