site_name: Architecture Tradeoff Analysis Methodology
site_description: 'DESCRIPTION All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/atam'
repo_url: 'https://github.com/dmccreary/atam'

nav:
  - Home: index.md
  - About: about.md
  - ATAM Process: atam-process.md
  - ATAM DB Selection Process: atam-db-process.md
  - Foundational Concepts:
    - Introduction: concepts/index.md
    - Four Vs of NoSQL: concepts/four-vs-of-nosql.md
    - Top NoSQL Strategies: concepts/top-10-nosql-tricks.md
    - Utility Tree: concepts/utility-tree.md
    - ACID vs. Base: concepts/acid-vs-base.md
    - Scalability: concepts/scalability.md
  - Database Types:
    - Introduction: db-types/index.md
    - Relational: db-types/relational/index.md
    - Analytical:
      - Introduction: db-types/analytical/index.md
      - Inman vs. Kimball: db-types/analytical/inman-vs-kimball.md
    - Key Value: db-types/key-value/index.md
    - Column Family: db-types/column-family/index.md
    - Graph: db-types/graph/index.md
    - Document: db-types/document/index.md
  - Case Studies:
    - Introduction: case-studies/index.md
    - STAR Case Study Process: case-studies/star-process.md
    - Deep Research: case-studies/deep-research.md
    - Amazon Shopping Cart: case-studies/amazon-shopping-cart.md
    - Memcache: case-studies/memchache.md
    - Craigslist: case-studies/craigslist.md
    - Cassandra: case-studies/cassandra.md
    - Facebook: case-studies/facebook.md
    - Friendster: case-studies/friendster.md
    - Google Knowledge Graph: case-studies/google-knowledege-graph.md
    - LinkedIn: case-studies/linkedin.md
    - TigerGraph: case-studies/tigergraph.md
  - Stories:
    - Introduction: stories/index.md
    - DynamoDB: stories/dynamodb/index.md
  - Prompts:
    - Introduction: prompts/index.md
    - Glossary Generation: prompts/glossary-generation.md
    - Top 10 Innovations: prompts/to-10-innovations.md
  - Bias: bias.md
  - Presentations: slides.md
  - Glossary: glossary.md
  - License: license.md
  - How We Built This Site: how-we-built-this-site.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  extra_css:
    - styles/custom.css
  # logo: img/my-icon.png
  # favicon: img/my-icon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX